name: wavelet_tutorial
dependencies:
  - python>=3.9,<3.12
  - jupyterlab
  - jupyter-dash 
  - ipykernel
  - scipy
  - numpy
  - pywavelets
  - pandas
  - pip
  - pip:
      - ipywidgets
      - matplotlib
      - cmaps
